### ISSUE TITLE
preserve `viewbox` attribute

### ISSUE THREAD

**Issue by bboyle** [Lorti/grunt-svg-symbols#8]
I see the template is generating a viewbox from `0 0 {width} {height}`

Some of the SVG source files I use don't have a width and height, but they do have a `viewBox`. They are being rendered as symbols with `viewBox="0 0"` — I'd rather they kept their viewBox.

Is that easy to do?

thanks :)

**Comment by Lorti** [comment]
Hi Ben, this should be fairly easy to do with a view changes to the code. Feel free to open up a pull request with your changes!

I have myself thought about it, but then decided to drop the idea. In my opinion each icon in an icon system should have the same size and all of the icons should look and feel cohesive. Otherwise, what's the point in an icon system?

**Comment by bboyle** [comment]
We pick and choose (largely from flaticon) so they come in wide variety of sizes.
They are all rendered the same size in our website. That's controlled with CSS ~:)

If you know an easy (automated) way to resize the SVGs, that would be a good alternative. Otherwise I will take a look at PR when I can :)

**Comment by Lorti** [comment]
Setting the size via CSS does not necessarily mean the icons match up. But I do see your point ;)

Changing the expression at https://github.com/Lorti/grunt-svg-symbols/blob/master/tasks/svg_symbols.js#L78 to something like `viewBox.width || options.width || result.info.width` may be enough for what you need. This way a fallback size is used if one of your SVGs does not contain a `viewBox`.

This should also have a flag, to not break existing pipelines…
